name: publish-extractor
description: Publish extractors to CDF extractors catalog
inputs:
  python-version:
    description: Python version to use
    default: '3.10'
  artifactory_username:
    description: Artifactory username
    required: true
  artifactory_password:
    description: Artifactory password
    required: true
  command:
    description: 'Publish action including: publish,sync,run-schema,schema,validate'
    required: true
  mainfest:
    description: Path to manifest file
  config-files:
    description: List of config files to validate
  wrong-config-files:
    description: List of config files that should fail to validate
  extra-uris:
    description: An optional list of URIs with trailing / to look for schemas in.
  schema:
    description: Input schema file
  output:
    description: Output schema file
  no-verify:
    description: Skip SSL verification
runs:
  using: composite
  steps:
    - name: Ensure python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build command
      uses: actions/github-script@v6
      with:
        script: |
          return '${{ inputs.no-verify }}'

    - name: Install publisher
      shell: bash
      run: pip install cognite-extractor-publisher --extra-index-url "https://${{ inputs.artifactory_username }}:${{ inputs.artifactory_password }}@cognite.jfrog.io/cognite/api/pypi/snakepit/simple"

    - name: Run publisher command
      shell: bash
      run: publish-extractor ${{ inputs.command }}
